name: Python API Test

on: [push, pull_request]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t order:dev -f 'dockerfiles/Dockerfile' ./

      - name: Run Docker Container and run test
        run: docker exec -it $(docker run --rm -d order:dev) /bin/sh -c 'cd api/ && python -m unittest'